baseURL = "https://nightowlkeyboards.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Night Owl Keyboards | Custom Mechanical Keyboards"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "projects"
name = "Projects"
weight = 1
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.footer]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "projects"
name = "Projects"
pre = ""
weight = 1
[[menu.main]]
URL = "about"
name = "About"
pre = ""
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
pre = ""
weight = 3
[[menu.main]]
URL = "https://instagram.com/nightowlkeyboards"
name = "Instagram"
pre = "instagram"
weight = "4"
[[menu.main]]
URL = "https://twitter.com/nightowlkb"
name = "Twitter"
pre = "twitter"
weight = "5"
[[menu.main]]
URL = "https://facebook.com/nightowlkeyboards"
name = "Facebook"
pre = "facebook"
weight = "6"
[[menu.main]]
URL = "https://discord.gg/mG2tB83"
name = "Discord"
pre = "discord"
weight = "7"
[params]
author = "Themefisher"
contact_form_action = "#"
description = ""
email = "demo@email.com"
google_analitycs_id = "UA-170915225-1"
location = "Austin, TX"
logo = "/images/header_logo_lg.png"
mobile = ""
multi_author = false
[params.gmap]
enable = true
gmap_api = ""
map_latitude = "30.2724374"
map_longitude = "-97.7446826"
map_marker = "images/marker.png"
[params.nav_button]
enable = false
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = []
[[params.social]]
icon = "instagram"
link = "https://instagram.com/nightowlkeyboards"
[[params.social]]
icon = "twitter"
link = "https://twitter.com/nightowlkb"
[[params.social]]
icon = "facebook"
link = "https://facebook.com/nightowlkeyboards"
[[params.social]]
icon = "discord"
link = "https://discord.gg/mG2tB83"
